src/components/Header/Nav/index.tsx

Manage now is active when user is on manager pool page.

fix: manager pool does not show that it is active

---

src/templates/PoolManager/index.tsx

manger pool will now open on the tab that is on the route

feat: manger pool will now open on the tab that is on the route

---

src/pages/shared/[id]/index.tsx
src/templates/Pool/ShareImageModal/index.tsx

refactor: changed image url

---

src/templates/PoolManager/FeeRewards/AvailableRewards/index.tsx
src/templates/PoolManager/FeeRewards/AvailableRewards/styles.ts
src/templates/PoolManager/FeeRewards/graphql.ts
src/templates/PoolManager/FeeRewards/index.tsx

refactor: updated rewards fee

---

src/components/Manage/TVMChart/Chart/index.tsx
src/components/Modals/ModalChooseNetwork/index.tsx
src/templates/Pool/NewPoolOperations/Form/Invest/index.tsx
src/templates/Pool/NewPoolOperations/Form/graphql.ts
src/templates/Pool/SharedImage/index.tsx

fix: fixed manager chart domain

---

src/utils/numerals.ts

Add documentation to the BNtoDecimal lib because it's pretty complicated and magical.
Hopefully this should clear all the confusion around it.

Add documentation to BNtoDecimal

---

src/components/ChartProducts/ChartAllocation.tsx
src/components/ChartProducts/TooltipAllocation/index.tsx
src/components/ChartProducts/TooltipAllocation/styles.ts
src/components/ChartProducts/index.tsx
src/gql/generated/kassandraApi.ts
src/gql/queries/kassandra/poolCharts-kassandra.gql
src/templates/Pool/SharedImage/ChartProducts/ChartAllocation.tsx
src/templates/Pool/SharedImage/ChartProducts/TooltipAllocation/index.tsx
src/templates/Pool/SharedImage/ChartProducts/TooltipAllocation/styles.ts
src/templates/Pool/SharedImage/ChartProducts/index.tsx

This should make the allocation chart actually useful and correct.

Refactor: allocation chart

---

src/components/QuestionsAndAnswers/styles.ts
src/hooks/query/useReferralDecrypt.tsx
src/services/IOperation.ts
src/services/operationV2.ts
src/templates/Pool/NewPoolOperations/Form/Invest/index.tsx
src/templates/PoolV2/Faqs/styles.ts
src/templates/PoolV2/Hero/index.tsx
src/templates/PoolV2/Hero/styles.ts
src/templates/PoolV2/index.tsx

Offer monetary compensation to Brokers.
Now the Broker address is passed through the URL.

feat: add referral commissions on pool operation

---

src/templates/Explore/CommunityPoolsTable/index.tsx

Pull Request with a change request has been accepted, this includes the requested modification.
- Enhancing type for IPoolsInfosProps in the CommunityPoolsTable

refactor: Enhancing type for IPoolsInfosProps in the CommunityPoolsTable

---

src/components/TextareaWithValueCounter/index.tsx
src/components/TextareaWithValueCounter/styles.ts
src/gql/generated/backendApi.ts
src/gql/generated/kassandraApi.ts
src/gql/queries/backend/savePool-backend.gql
src/gql/queries/kassandra/poolStrategy-kassandra.gql
src/hooks/query/useSavePool.tsx
src/store/reducers/poolCreationSlice.ts
src/templates/Manage/CreatePool/SetDetails/PoolDetails/index.tsx
src/templates/Manage/CreatePool/graphql.ts
src/templates/Manage/CreatePool/index.tsx
src/templates/PoolManager/Details/Strategy/index.tsx
src/templates/PoolManager/Details/Strategy/styles.ts

Introduce a new input 'short_summary' in the pool creation and update processes.
- Implement a new component called 'TextareaWithValueCounter
- Integrate this component into pool creation and update processes
- Update the query to accommodate the new 'short_summary' field

feat: add short summary in update and create pool

---

src/templates/Pool/NewPoolOperations/Form/Invest/index.tsx

Investor, despite being authorized, is unable to join the pool
* Transform address in lower case when we check investor is allowed
* Refactor imports to use alias

fix: check if investor are allowed

---

src/components/TitleSection/index.tsx
src/templates/PoolManager/ActivityCard/TransactionInfo/index.tsx
src/templates/PoolManager/ActivityCard/UserInfo/index.tsx
src/templates/PoolManager/ActivityCard/UserInfo/styles.ts
src/templates/PoolManager/Details/Strategy/index.tsx
src/templates/PoolManager/Details/Strategy/styles.ts

Corrections for errors found in the last review of the new pool page.
- add titleSection to short_summary in Details tab on manager pool page.
- include nickname in UserInfo component within ActivityCard.
- change text in TransactionInfo component within ActivityCard.

Refactor: qa the new pool page

---

src/templates/Manage/CreatePool/Review/PoolReview/index.tsx
src/templates/PoolV2/NewPoolOperations/Form/Withdraw/index.tsx

User can't withdraw wrapped tokens and when created pool in review step does not calc price in
* Verify token is wrapped
* Normalize percentage allocation

fix: withdraw and create pool

---

src/components/QuestionsAndAnswers/styles.ts
src/components/TokenWithNetworkImage/index.tsx
src/hooks/useAllocationInfo.tsx
src/templates/Explore/CommunityPoolsTable/index.tsx
src/templates/Explore/CommunityPoolsTable/styles.ts
src/templates/PoolManager/Activity/index.tsx
src/templates/PoolManager/ActivityCard/TokenChangeUpdate/index.tsx
src/templates/PoolManager/ActivityCard/TokenInfo/index.tsx
src/templates/PoolManager/ActivityCard/TokenInfo/styles.ts
src/templates/PoolManager/ActivityCard/TransactionInfo/index.tsx
src/templates/PoolManager/ActivityCard/UserInfo/index.tsx
src/templates/PoolManager/ActivityCard/UserInfo/styles.ts
src/templates/PoolManager/ActivityCard/index.tsx
src/templates/PoolManager/utils/index.ts
src/templates/PoolV2/Activity/index.tsx
src/templates/PoolV2/Allocations/index.tsx
src/templates/PoolV2/Hero/MyAsset/index.tsx
src/templates/PoolV2/Hero/SharedImage/ChartProducts/index.tsx
src/templates/PoolV2/Hero/index.tsx
src/templates/PoolV2/Hero/styles.ts
src/templates/PoolV2/Overview/TokenDescription/index.tsx

Corrections for errors found in the last review of the new pool page.
- add condition to apply shadow to the text in the TokenDescription component
- add a link to the profile page in the UserInfo component
- limit size of token list in table in CommunityPools component
- add token warps in useAllocationInfo funciton in useAllocation hook
- add animation in QuestionsAndAnswers component
- add default image to TokenWithNetworkImage component
- add Tooltip with symbol the token in AcitivityCard
- fix skeletonLoading mobile on hero in pool page

fix: qa new pool page

---

src/templates/PoolManager/Details/PoolImage/index.tsx
src/templates/PoolManager/utils/index.ts

Missing the value for shortSummary in the sendPoolData function within the PoolImage component
- add shortSummary on sendPoolData function in PoolImage component
- increase decimal places in sharesPrice in the getActivityInfo function

refactor: add shortSummary in PoolImage component

---

src/components/Inputs/InputNumber/styles.ts
src/constants/tokenAddresses.ts
src/gql/generated/kassandraApi.ts
src/gql/queries/kassandra/poolAssets-kassandra.gql
src/store/reducers/rebalanceAssetsSlice.ts
src/templates/PoolManager/Details/PoolImage/index.tsx
src/templates/PoolManager/ManageAssets/AddLiquidity/AddLiquidityOperation/index.tsx
src/templates/PoolManager/ManageAssets/SetNewWeights/AllocationsTable/PoolToken/index.tsx
src/templates/PoolManager/ManageAssets/SetNewWeights/AllocationsTable/PoolToken/styles.ts
src/templates/PoolManager/ManageAssets/SetNewWeights/ExecutionPeriod/styles.ts
src/templates/PoolManager/ManageAssets/SetNewWeights/index.tsx
src/templates/PoolManager/ManageAssets/SetNewWeights/styles.ts
src/utils/updateAssetsToV2.ts

Add a warning card to the pool rebalancing table when the rebalancing process is too aggressive.
- add warning card in SetNewWeights component
- add min allocation in AddLiquidityOperation component
- change the Heimdall link to coingecko in the PoolToken component

refactor: add check values in rebalance pool

---

src/components/DepositFee/index.tsx
src/components/DepositFee/styles.ts
src/hooks/useManagePoolController.tsx
src/templates/Manage/CreatePool/ConfigureFee/FeeBreakdown/index.tsx
src/templates/Manage/CreatePool/ConfigureFee/FeeConfig/index.tsx
src/templates/Manage/CreatePool/ConfigureFee/FeeConfig/styles.ts
src/templates/PoolManager/FeeRewards/index.tsx

Previously, users were unable to modify fee values after creating a pool. Now, we have added a feature on the FeeRewards tab within the Manager page, allowing them to change the fee.
- Create DepositFee component
- create setJoinFees function in useManagePoolController hook
- add DepositFee component in Create Pool 
- add DepositFee component in FeeRewards Tab

feat: add DepositFee component in FeeReward tab

---

src/components/Modals/ModalProfile/styles.ts
src/services/ParaSwap.ts
src/templates/PoolV2/NewPoolOperations/Form/Invest/index.tsx

Corrections for errors found in the last review of the new pool page.
-  enhance error handling for price calculation in poolOperation

refactor: qa pool page

---

src/gql/generated/backendApi.ts
src/gql/generated/kassandraApi.ts
src/gql/queries/kassandra/poolJoins-kassandra.gql
src/gql/queries/kassandra/poolVolumeData-kassandra.gql
src/hooks/query/useSendUserProfile.tsx
src/hooks/useCreatePool.tsx
src/hooks/useLocalStorage.tsx
src/templates/Manage/CreatePool/index.tsx
src/templates/Manage/GetStarted/index.tsx
src/templates/Manage/Overview/index.tsx
src/templates/Manage/Overview/styles.ts
src/templates/Manage/index.tsx

We received feedback from users that the volume query was incorrect, the user's profile image was not appearing, and a notice should be added regarding the recently created pool being indexed
- create useLocalStorage hook
- add feedback during pool indexing in manage page
- correct volume query on manager and pool page
- add uploadImage in sendUserData hook

feat: implement feedback during pool indexing and incorrect volume query

---

src/components/Modals/ModalProfile/index.tsx

Corrections for errors found in the last review
-add getAddress function in modal profile

fix: qa modal profile

---

src/services/ParaSwap.ts

In the latest update, investing with the token inside the pool is encountering an error.

fix: invest with pool token in getAmountsOut

---

src/components/ChartProducts/ChartPrice.tsx
src/templates/PoolV2/Hero/ShareImageModal/index.tsx
src/templates/PoolV2/Hero/ShareImageModal/styles.ts

Bug fixes found on the pool page.
- fix: add domain to chart in ChartPrice component
- fix: remove WarningCard from image generated in ShareImageModal component

Fix: qa pool page

---

src/services/operationV2.ts
src/templates/PoolManager/ManageAssets/SetNewWeights/AllocationsTable/PoolToken/styles.ts
src/templates/PoolV2/NewPoolOperations/Form/Invest/index.tsx
src/templates/PoolV2/NewPoolOperations/Form/Withdraw/index.tsx

The race condition in poolOperation has been fixed

fix: race condition in pool operation

---

src/components/Breadcrumb/BreadcrumbItem/styles.ts
src/components/Header/Nav/index.tsx
src/components/Modals/ModalKacy/index.tsx
src/gql/generated/kassandraApi.ts
src/gql/queries/kassandra/managerTotalManaged-kassandra.gql
src/hooks/query/useManagerTotalTVL.tsx
src/templates/Manage/index.tsx
src/templates/PoolManager/FeeRewards/FeesChart/index.tsx
src/templates/PoolV2/index.tsx
src/templates/Profile/index.tsx

We identified bugs on the management and profile pages.
- add point-event to the active state in Breadcrumb component
- update blog link in Header
- add manager total tvl value in profile page
- add max domain value in chart
- fix pool existence check in the manager page

fix: qa profile and manager page

---

src/components/Header/HeaderButtons/SvgButtons.tsx
src/components/Header/HeaderButtons/index.tsx
src/components/Header/HeaderButtons/styles.ts
src/components/Modals/ModalSubgraphStatus/index.tsx
src/components/Modals/ModalSubgraphStatus/styles.ts
src/components/StatusIndicator/index.tsx
src/components/StatusIndicator/styles.ts
src/constants/tokenAddresses.ts
src/hooks/query/useLatestBlock.tsx
src/pages/api/subgraph/[id]/index.ts
src/pages/api/subgraph/index.ts
src/pages/api/subgraph/status/index.ts

A route was created to check the status and blocks of the subgraph, along with a component in the header that displays the subgraph status on the front end.
- create subgraphStatus modal
- create StatusIndicator component
- create useLatestBlock hook
- create subgraph api route

feat: create subgraph status 

---

src/components/Header/HeaderButtons/index.tsx
src/components/Modals/ModalChooseNetwork/index.tsx
src/components/Modals/ModalProfile/styles.ts
src/components/Modals/ModalSubgraphStatus/index.tsx
src/components/Modals/ModalSubgraphStatus/styles.ts
src/components/StatusIndicator/styles.ts
src/templates/Gov/CreateProposal/index.tsx
src/templates/PoolManager/FeeRewards/AvailableRewards/index.tsx
src/templates/PoolManager/FeeRewards/FeesChart/index.tsx
src/templates/PoolManager/ManageAssets/SetNewWeights/ExecutionPeriod/index.tsx
src/utils/date.ts

We identified bugs on the manager page and header component.
- add diffTime in ModalSubgraphStatus component
- create handleChangeChain function
- update background in Profile and SubgraphStatus modals
- update useEffect depency in AvailableRewards component

fix: qa manager page and header

---

src/components/Modals/ModalSubgraphStatus/index.tsx

This change involves a review and improvement of the text within the SubgraphStatus component
- modified text in the SubgraphStatus component

refactor: modified text in the SubgraphStatus component

---

src/components/Modals/ModalSubgraphStatus/index.tsx
src/components/Modals/ModalSubgraphStatus/styles.ts

Update title text and remove subtitle in SubgraphStatus component

refactor: update subgraph component

---

src/components/MarkdownEditor/index.tsx
src/components/VotingPower/index.tsx
src/templates/Gov/CreateProposal/AdvancedProposalOption/index.tsx
src/templates/Gov/CreateProposal/index.tsx
src/templates/Gov/Proposals/Proposal/index.tsx

Update the text on the create proposal page

refactor: modified text in create proposal page

---

.gitignore
next.config.js
package.json
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts
src/hooks/useBridge.tsx
src/hooks/useCreatePool.tsx
src/hooks/useERC20.tsx
src/hooks/useGov.tsx
src/hooks/useManagePoolController.tsx
src/hooks/useStaking.tsx
src/hooks/useTransaction.tsx
src/hooks/useVotings.tsx
src/pages/_error.tsx
src/templates/PoolV2/NewPoolOperations/Form/Invest/index.tsx
src/templates/PoolV2/NewPoolOperations/Form/Withdraw/index.tsx
yarn.lock

add Sentry, which is an error tracking tool that displays all failures in your stack as they occur

feat: add sentry

---

src/components/Modals/ModalAlert/index.tsx
src/components/Modals/ModalAlert/styles.ts
src/components/Modals/ModalAlertTransferOwnership/index.tsx
src/components/Modals/ModalAlertTransferOwnership/styles.ts
src/constants/tokenAddresses.ts
src/gql/generated/kassandraApi.ts
src/gql/queries/kassandra/managerPoolInfo-kassandra.gql
src/hooks/useERC20.tsx
src/hooks/useManagePoolController.tsx
src/hooks/useTransaction.tsx
src/pages/_app.tsx
src/pages/api/subgraph/status/index.ts
src/pages/ownership-claim.tsx
src/store/reducers/modalAlertText.ts
src/templates/OwnershipClaim/index.tsx
src/templates/OwnershipClaim/styles.ts
src/templates/PoolManager/Details/PoolStrategyControl/index.tsx
src/templates/PoolManager/Details/PoolStrategyControl/styles.ts
src/templates/PoolManager/Details/TransferOwnership/index.tsx
src/templates/PoolManager/Details/TransferOwnership/styles.ts
src/templates/PoolManager/Details/index.tsx
src/templates/PoolManager/Details/styles.ts
src/templates/PoolManager/index.tsx
src/utils/substr.ts

here components have been added to change the roles of the strategist and the pool owner, along with adapting the manager page for the strategist.
- create ownership-claim page
- create TransferOnweship component
- create PoolStrategyControl component
- create ModalAlertTransferOwnership component

feat: create TransferOnweship and PoolStrategyControl component

---

src/services/operationV2.ts
src/templates/PoolV2/NewPoolOperations/Form/Invest/index.tsx

On the Polygon chain, we are experiencing occasional issues where the website estimates a gas limit below what is required, resulting in transaction errors.
- Add gasLimit parameter to investment and withdrawal operations in OperationV2

Feat: add gasLimit in operationV2

---

src/gql/generated/kassandraApi.ts
src/gql/queries/kassandra/managerPoolInfo-kassandra.gql
src/templates/PoolManager/index.tsx
src/templates/PoolV2/Staking/index.tsx

fix check manager in pool manager

fix: qa poolmanager page

---

src/constants/tokenAddresses.ts
src/pages/api/subgraph/[id]/index.ts
src/pages/api/subgraph/index.ts
src/templates/PoolV2/NewPoolOperations/Form/InputAndOutputValueToken/index.tsx

I updated the route to now fetch the current block via RPC instead of the subgraph query. Additionally, I've added functionality to return the time difference between the current block and the block being processed by the subgraph.

Refactor: update subgraph route

---

src/components/StakeCard/index.tsx
src/constants/pools.ts
src/hooks/useCreatePool.tsx
src/templates/StakeFarm/Farm/index.tsx

Added 3 new farming pools: High risk, medium risk, and low risk.

feat: add news pools

---

src/components/FundCardNew/styles.ts
src/templates/Explore/SliderPoolList/styles.ts
src/templates/Explore/index.tsx
src/templates/Explore/styles.ts

Carousels in the Explore page had a few issues, this PR aims to solve them.
1. Fix issues with padding and margins inside the carousel sliders
2. Fix return slider button not working
3. Made sure all the paddings and margins are the same across all sliders
4. Fix some size variation issues
5. Improved responsiveness of the carousel in general

refactor: carousel changes

---

src/templates/StakeFarm/index.tsx
src/templates/StakeFarm/newStakeindex.tsx
src/templates/StakeFarm/newStakestyles.ts
src/templates/StakeFarm/styles.ts

Restore old stake page until its new design is finished.
Please delete options that are not relevant.
1. Reverted Stake page to old design

refactor: restore old stake page

---

package.json
src/hooks/query/useExplorePools.tsx
src/hooks/query/usePoolsWithJoinBrokerFee.tsx
src/templates/Explore/index.tsx
yarn.lock

refactor: add lazyloading explore page

---

src/components/Header/HeaderButtons/index.tsx
src/templates/Explore/PoolsData/index.tsx

Very small PR to fix a header network connection issue when the user is not on one of the allowed networks.
Fixes 2 (issues)
1. Adds a fix to when the user is not on the allowed networks
2. Add a missing key to a map

fix: header network error

---

src/components/Breadcrumb/index.tsx
src/components/ChartProducts/index.tsx
src/components/FundCardNew/FundStatus/index.tsx
src/templates/Explore/CommunityPoolsTable/index.tsx
src/templates/Explore/NewCommunityPoolsTable/index.tsx
src/templates/Explore/PoolsData/styles.ts
src/templates/Explore/SliderPoolList/styles.ts
src/templates/Manage/CreatePool/Review/PoolReview/index.tsx
src/templates/Pool/SharedImage/ChartProducts/index.tsx
src/templates/PoolV2/Hero/SharedImage/ChartProducts/index.tsx
src/templates/PoolV2/Overview/index.tsx
src/templates/Profile/Portfolio/AssetsTable/index.tsx

Changes made after the first round of Q/A.

refactor: qa changes

---

src/constants/pools.ts
src/hooks/query/useSkatePoolPowerVoting.tsx
src/templates/StakeFarm/index.tsx

refactor: add loading in stake page

---

src/constants/pools.ts
src/hooks/query/useInvestmentPools.tsx
src/hooks/query/useLiquidityPool.tsx
src/hooks/query/usePoolsPriceList.tsx
src/templates/StakeFarm/StakeListCard/index.tsx
src/templates/StakeFarm/index.tsx

Corrected incorrect value of yourstake on the stake page in response to user YarDev's error report

Fix: incorrect your stake value

---

src/pages/api/tokens.ts
src/store/reducers/poolCreationSlice.ts

add getAddress in tokens route

fix: add getAddress in tokens route

---

src/components/Header/HeaderButtons/index.tsx
src/constants/tokenAddresses.ts
src/hooks/query/useInvestmentPools.tsx
src/hooks/query/useLiquidityPool.tsx
src/hooks/query/useSkatePoolPowerVoting.tsx
src/hooks/useBatchRequests.tsx
src/hooks/useERC20.tsx
src/hooks/useGasFee.tsx
src/hooks/useGov.tsx
src/hooks/useStaking.tsx
src/hooks/useTransaction.tsx
src/services/operationV2.ts
src/templates/StakeFarm/utils.ts
src/utils/provider.ts

I've added the `FallbackProvider` from ethers.js at key points in the app to reduce RPC call failures. This change should improve the app's stability.

refactor: update rpcs
